# Generated by Django 5.1.6 on 2025-02-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('pipeline', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('markets', models.TextField(blank=True, null=True)),
                ('social_media', models.JSONField(blank=True, default=dict)),
                ('videos', models.JSONField(blank=True, default=list)),
                ('interfaces', models.JSONField(blank=True, default=list)),
                ('founders', models.JSONField(blank=True, default=dict)),
                ('differentiators', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('clients', models.JSONField(blank=True, default=list)),
                ('funding_raised', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cash_runway', models.CharField(blank=True, max_length=100, null=True)),
                ('revenue_last_12m', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('revenue_last_month', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('funding_rounds', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
