# Generated by Django 5.1.6 on 2025-02-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupapp', '0002_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='funding_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='founders',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='startup',
            name='pipeline',
            field=models.CharField(blank=True, choices=[('pre_seed', 'Pre-Seed'), ('seed', 'Seed'), ('series_a', 'Series A'), ('series_b', 'Series B'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='startup_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
