# Generated by Django 5.1.6 on 2025-02-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupapp', '0003_startup_funding_currency_alter_startup_founders_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startup',
            old_name='name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='startup',
            old_name='funding_raised',
            new_name='rev_last_12_months',
        ),
        migrations.RenameField(
            model_name='startup',
            old_name='revenue_last_12m',
            new_name='rev_last_month',
        ),
        migrations.RenameField(
            model_name='startup',
            old_name='funding_rounds',
            new_name='rounds',
        ),
        migrations.RenameField(
            model_name='startup',
            old_name='revenue_last_month',
            new_name='total_funding',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='funding_currency',
        ),
        migrations.AddField(
            model_name='startup',
            name='files',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='founded_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='incorporated',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='last_contact',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='milestone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='revenue_model',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='sources',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='startup',
            name='tagline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='startup',
            name='clients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='interfaces',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='pipeline',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='videos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='startup',
            index=models.Index(fields=['startup_id'], name='startupapp__startup_3ba34c_idx'),
        ),
        migrations.AddIndex(
            model_name='startup',
            index=models.Index(fields=['item_name'], name='startupapp__item_na_799e68_idx'),
        ),
    ]
