# Generated by Django 5.1.6 on 2025-02-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupapp', '0004_rename_name_startup_item_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='cash_runway',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='rev_last_12_months',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='rev_last_month',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='total_funding',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
