# Generated by Django 5.1.6 on 2025-02-23 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupapp', '0005_alter_startup_cash_runway_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='cash_runway',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='clients',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='description',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='differentiators',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='files',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='founded_date',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='founders',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='incorporated',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='interfaces',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='last_contact',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='milestone',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='rev_last_12_months',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='rev_last_month',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='revenue_model',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='rounds',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='social_media',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='tagline',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='total_funding',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='videos',
        ),
        migrations.CreateModel(
            name='StartupApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founders', models.JSONField(blank=True, default=list)),
                ('social_media', models.JSONField(blank=True, default=dict)),
                ('tagline', models.TextField(blank=True, null=True)),
                ('milestone', models.TextField(blank=True, null=True)),
                ('revenue_model', models.TextField(blank=True, null=True)),
                ('last_contact', models.DateTimeField(blank=True, null=True)),
                ('incorporated', models.CharField(blank=True, max_length=100, null=True)),
                ('founded_date', models.DateField(blank=True, null=True)),
                ('differentiators', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('interfaces', models.TextField(blank=True, null=True)),
                ('total_funding', models.CharField(blank=True, max_length=50, null=True)),
                ('cash_runway', models.CharField(blank=True, max_length=50, null=True)),
                ('rev_last_12_months', models.CharField(blank=True, max_length=50, null=True)),
                ('rev_last_month', models.CharField(blank=True, max_length=50, null=True)),
                ('rounds', models.IntegerField(blank=True, null=True)),
                ('clients', models.TextField(blank=True, null=True)),
                ('videos', models.TextField(blank=True, null=True)),
                ('files', models.TextField(blank=True, null=True)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='startupapp.startup')),
            ],
        ),
    ]
