# Generated by Django 5.1.6 on 2025-02-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupapp', '0006_remove_startup_cash_runway_remove_startup_clients_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startupapplication',
            old_name='description',
            new_name='brief_description',
        ),
        migrations.RenameField(
            model_name='startupapplication',
            old_name='incorporated',
            new_name='primary_contact_title',
        ),
        migrations.RenameField(
            model_name='startupapplication',
            old_name='differentiators',
            new_name='skills_or_markets',
        ),
        migrations.RemoveField(
            model_name='startupapplication',
            name='cash_runway',
        ),
        migrations.RemoveField(
            model_name='startupapplication',
            name='files',
        ),
        migrations.RemoveField(
            model_name='startupapplication',
            name='founded_date',
        ),
        migrations.RemoveField(
            model_name='startupapplication',
            name='founders',
        ),
        migrations.RemoveField(
            model_name='startupapplication',
            name='interfaces',
        ),
        migrations.RemoveField(
            model_name='startupapplication',
            name='last_contact',
        ),
        migrations.RemoveField(
            model_name='startupapplication',
            name='milestone',
        ),
        migrations.RemoveField(
            model_name='startupapplication',
            name='rev_last_12_months',
        ),
        migrations.RemoveField(
            model_name='startupapplication',
            name='rev_last_month',
        ),
        migrations.RemoveField(
            model_name='startupapplication',
            name='revenue_model',
        ),
        migrations.RemoveField(
            model_name='startupapplication',
            name='rounds',
        ),
        migrations.RemoveField(
            model_name='startupapplication',
            name='social_media',
        ),
        migrations.RemoveField(
            model_name='startupapplication',
            name='tagline',
        ),
        migrations.RemoveField(
            model_name='startupapplication',
            name='total_funding',
        ),
        migrations.RemoveField(
            model_name='startupapplication',
            name='videos',
        ),
        migrations.AddField(
            model_name='startup',
            name='cash_runway',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='clients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='differentiators',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='files',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='founded_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='incorporated',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='interfaces',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='milestone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='rev_last_12_months',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='rev_last_month',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='revenue_model',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='rounds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='tagline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='total_funding',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='videos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startupapplication',
            name='amount_raising',
            field=models.CharField(blank=True, default='N/A', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='startupapplication',
            name='application_id',
            field=models.CharField(db_index=True, default='TEMP_APP_ID', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='startupapplication',
            name='average_score',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='startupapplication',
            name='fund_stage',
            field=models.CharField(blank=True, default='Unknown', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='startupapplication',
            name='primary_contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='startupapplication',
            name='valuation',
            field=models.CharField(blank=True, default='N/A', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='startupapplication',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='startup_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
