# Generated by Django 5.1.6 on 2025-02-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupapp', '0007_rename_description_startupapplication_brief_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='founders',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='startup',
            name='last_contact',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='social_media',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='startup',
            name='sources',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='startup',
            name='startup_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='StartupApplication',
        ),
    ]
