# Generated by Django 5.1.6 on 2025-02-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupapp', '0009_startupapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='cash_runway',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='incorporated',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='rev_last_12_months',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='rev_last_month',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='rounds',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='total_funding',
        ),
        migrations.AddField(
            model_name='startup',
            name='financials',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='startup',
            name='registration_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='startupapplication',
            name='primary_contact_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='startupapplication',
            name='progress_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='clients',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='startup',
            name='markets',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='startup',
            name='videos',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
