# Generated by Django 5.1.6 on 2025-02-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupapp', '0010_remove_startup_cash_runway_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='financials',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='registration_info',
        ),
        migrations.RemoveField(
            model_name='startupapplication',
            name='primary_contact_title',
        ),
        migrations.RemoveField(
            model_name='startupapplication',
            name='progress_status',
        ),
        migrations.AddField(
            model_name='startup',
            name='cash_runway',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='incorporated',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='rev_last_12_months',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='rev_last_month',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='rounds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='total_funding',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='clients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='markets',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='videos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
