# Generated by Django 5.1.6 on 2025-02-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupapp', '0011_remove_startup_financials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupapplication',
            name='contact_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='startupapplication',
            name='customer_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='startupapplication',
            name='financials',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='startupapplication',
            name='primary_contact_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='startupapplication',
            name='progress_status',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='startupapplication',
            name='quality_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startupapplication',
            name='registration_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='startupapplication',
            name='videos',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
