# Generated by Django 5.1.6 on 2025-02-27 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startupapp', '0012_startupapplication_contact_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startupapplication',
            old_name='quality_score',
            new_name='average_score',
        ),
        migrations.RenameField(
            model_name='startupapplication',
            old_name='pitch',
            new_name='brief_description',
        ),
        migrations.RenameField(
            model_name='startupapplication',
            old_name='business_stage',
            new_name='fund_stage',
        ),
    ]
