# Generated by Django 5.1.6 on 2025-02-27 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startupapp', '0013_rename_quality_score_startupapplication_average_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startupapplication',
            old_name='fund_stage',
            new_name='business_stage',
        ),
    ]
