# Generated by Django 5.1.6 on 2025-02-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupapp', '0014_rename_fund_stage_startupapplication_business_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupapplication',
            name='applicant_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
