# Generated by Django 5.1.6 on 2025-02-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupapp', '0015_alter_startupapplication_applicant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='total_funding',
        ),
        migrations.AddField(
            model_name='startup',
            name='total_funding_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='total_funding_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
