# Generated by Django 5.1.6 on 2025-03-10 15:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupapp', '0016_remove_startup_total_funding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupAIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, null=True)),
                ('industry_classification', models.CharField(blank=True, max_length=50, null=True)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='startupapp.startup')),
            ],
        ),
    ]
